force-app/main/default/objects/Authorized__c/Authorized__c.object-meta.xml
<CustomObject>
    <label>Authorized</label>
    <nameField>
        <label>Authrized Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authorizeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Authorized__c/fields/instance_url__c.field-meta.xml
<CustomField>
    <fullName>instance_url__c</fullName>
    <label>instance_url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataDeployController.cls
public with sharing class MetadataDeployController 
{
   
	public String ZipData { get; set; }	
	
	public MetadataService.AsyncResult AsyncResult {get; private set;}
	
     @AuraEnabled(cacheable=true)
	public String getPackageXml()
	{
		return '<?xml version="1.0" encoding="UTF-8"?>' + 
			'<Package xmlns="http://soap.sforce.com/2006/04/metadata">' + 
    			'<types>' + 
        			'<members>HelloWorld</members>' +
        			'<name>ApexClass</name>' + 
    			'</types>' + 
    			'<version>26.0</version>' + 
			'</Package>';		
	}
	
	public String getHelloWorldMetadata()
	{
		return '<?xml version="1.0" encoding="UTF-8"?>' +
			'<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">' +
			    '<apiVersion>28.0</apiVersion>' + 
			    '<status>Active</status>' +
			'</ApexClass>';		
	}
	
	public String getHelloWorld()	
	{
		return 'public class HelloWorld' + 
			'{' + 
				'public static void helloWorld()' +
				'{' + 
					'System.debug(\' Hello 123World\');' +
				'}' +
			'}';
	}
	// @AuraEnabled(cacheable=true)
	public  void deployZip()
	{
		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Deploying...'));

		// Deploy zip file posted back from the page action function				
		MetadataService.MetadataPort service = createService();
		MetadataService.DeployOptions deployOptions = new MetadataService.DeployOptions();
        deployOptions.allowMissingFiles = false;
        deployOptions.autoUpdatePackage = false;
        deployOptions.checkOnly = false;
        deployOptions.ignoreWarnings = false;
        deployOptions.performRetrieve = false;
        deployOptions.purgeOnDelete = false;
        deployOptions.rollbackOnError = true;
        deployOptions.testLevel = 'NoTestRun';
        deployOptions.singlePackage = true;		
		AsyncResult = service.deploy(ZipData, DeployOptions);				
		//return null;
	}	
	// @AuraEnabled(cacheable=true)
	public  void checkAsyncRequest()
	{	
		// Check the status of the retrieve request
		MetadataService.MetadataPort service = createService();
		MetadataService.DeployResult deployResult = service.checkDeployStatus(AsyncResult.Id, true);
		if(deployResult.done)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Deployment complete'));

			// Deployment errors?
			if(deployResult.details!=null && deployResult.details.componentFailures!=null)
				for(MetadataService.DeployMessage deployMessage : deployResult.details.componentFailures)
					if(deployMessage.problem!=null)
						ApexPages.addMessage(
							new ApexPages.Message(ApexPages.Severity.Error, 
								deployMessage.fileName + 
									' (Line: ' + deployMessage.lineNumber + ': Column:' + deployMessage.columnNumber + ') : ' + 
										deployMessage.problem));
			AsyncResult = null;
		}
		else
		{ 
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Deploying...'));
		}	
		//return null;
	}
	
	private static MetadataService.MetadataPort createService() {
   
    Authorized__c authorizedRecord = [SELECT access_token__c, instance_url__c  FROM Authorized__c LIMIT 1];
    String accessToken = authorizedRecord.access_token__c;
    String instanceUrl = authorizedRecord.instance_url__c;    
    String endpoint_x = instanceUrl + '/services/Soap/m/42.0';
    MetadataService.MetadataPort service = new MetadataService.MetadataPort();
    service.endpoint_x = endpoint_x;
   
    service.SessionHeader = new MetadataService.SessionHeader_element();
    service.SessionHeader.sessionId = accessToken;

    return service;
}

}